#!/usr/bin/env bash
# This script is used for FizzBuzz game
n=1

while [ $n -le 100 ]
do
    if [ $(( n % 3 )) -eq 0 -a $(( n % 5 )) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $(( n % 3 )) -eq 0 ]
    then
        echo "Fizz"
    elif [ $(( n % 5 )) -eq 0 ]
    then
        echo "Buzz"
    else
        echo $n
    fi
    n=$(( n + 1 ))
done
