#!/usr/bin/env bash
# This script prints "bad luck" 4th iteration, "good luck" on the 8th iteration, and "Best School" iterations.
n=1

while [ $n -le 10 ]
do
    if [ $n -eq 4 ]
    then
        echo "bad luck"
    elif [ $n -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    n=$(( n + 1 ))
done
